--- 
output_dir: private_output
data_sources: 
- type: filesystem_unified
  items_root: /
  layouts_root: /

# Custom settings

# Use rsync + ssh for live site. To deploy:
#
#   % rake deploy:rsync
deploy:
  default:
    dst: "./tmp/"
    options: ['-ave ssh', '--exclude=.DS_Store', '--exclude=*~']

# domain to which this site is deployed
base_url: http://ttyn.me

google_analytics:
  domain: ttyn.me
  site_id: UA-7206667-1

# currently used by logo
site_name: it's not me@another universe

# number of full featured posts to display on front
featured_count: 1

# number of excerpted posts to display on front
excerpt_count: 0

# number of other articles to reference at bottom of each article
other_articles_max: 0

# DISQUS Site Shortname. Comment out to disable.
#disqus_shortname: ttyn
